In [ ]:
import numpy as np
from skimage.filters import median
from spatial_filter import medf
#img=np.random.randint(10,size=(5,5))
img1=np.array([[7, 1, 6, 7,2],
 [9 ,1, 8, 9, 5],
 [4 ,4 ,6 ,3 ,0],
 [8 ,8, 1, 8, 7],
 [0 ,0 ,7, 7 ,5]])
sorted_knl=np.sort(img1, axis=None, kind='quicksort')
print(len(sorted_knl))
print(img1)
img2=medf(3,img1)
print(img2)
img3=median(img1,mode='constant',cval=0.0)
print(img3)

In [ ]:
import numpy as np
def pad_img(img,size):
    m,n=img.shape
    pad_len=int((size-1)/2)#padding length for each edge
    padded_img=np.zeros([m+size-1,n+size-1])
    for i in range(pad_len, pad_len+m):
        for j in range(pad_len, pad_len+n):
            padded_img[i,j]=img[i-pad_len,j-pad_len]
    return padded_img

img1=np.array([[7, 1, 6, 7,2],
 [9 ,1, 8, 9, 5],
 [4 ,4 ,6 ,3 ,0],
 [8 ,8, 1, 8, 7],
 [0 ,0 ,7, 7 ,5]])

img=pad_img(img1,3)
print(img)
print(img.shape)

In [ ]:
import numpy as np
a=np.array([[7, 1, 6, 7,2],
 [9 ,1, 8, 9, 5],
 [4 ,4 ,6 ,3 ,0],
 [8 ,8, 1, 8, 7],
 [0 ,0 ,7, 7 ,5]])
b=np.sort(a,axis=None)
print(a)
print(b)

In [ ]:
#import numpy as np
def medft(size,img):
    m,n=img.shape
    kernel=np.zeros([size,size])
    pad_len=int((size-1)/2)
    padded_img=pad_img(img, size)
    new_img=np.zeros([m,n],dtype=np.uint8)
    for i in range(pad_len,pad_len+m):
        for j in range(pad_len,pad_len+n):
            for s in range(0,size):
                for t in range(0,size):
                    p=i-pad_len+s
                    q=j-pad_len+t
                    kernel[s,t]=padded_img[p,q]
                    #print('s',s,'t',t, 'i',p,'j',q)
            sorted_knl=np.sort(kernel, axis=None, kind='quicksort')
            #print(sorted_knl)
            med=sorted_knl[int((size*size-1)/2)]
            new_img[i-pad_len,j-pad_len]=med
    return new_img

a=np.array([[7, 1, 6, 7,2],
            [9 ,1, 8, 9, 5],
            [4 ,4 ,6 ,3 ,0],
            [8 ,8, 1, 8, 7],
            [0 ,0 ,7, 7 ,5]])
print(medft(3,a))

In [ ]:

img1=np.array([[7, 1, 6, 7,2],
 [9 ,1, 8, 9, 5],
 [4 ,4 ,6 ,3 ,0],
 [8 ,8, 1, 8, 7],
 [0 ,0 ,7, 7 ,5]])

medf(3,img1)

In [5]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from spatial_filter import knl_generator, filter
from global_thresholding import find_th, bi_imag
from skimage.filters import threshold_otsu, threshold_local
from skimage.color import rgb2gray

#test linear filter on 'salt-pepper noise' corrupted image
#test median filter on 'salt-pepper noise'

PATH='testcases\\'
NAME='clr3noise0_1.png-f_median_5.png'
'''
PATH='D:\\lab2\\'
NAME='origin1.png'
'''
img=cv2.imread(PATH+NAME,0)
img=rgb2gray(img)
'''
av3=knl_generator('average', 3, 0)
av5=knl_generator('average', 5, 0)
m3=knl_generator('median', 3, 0)
m5=knl_generator('median', 5, 0)
sobel_h=knl_generator('sobel_h', 0, 0)
sobel_v=knl_generator('sobel_v', 0, 0)
img_h=filter(img, 'linear', sobel_h)
img_v=filter(img, 'linear',sobel_v)
cv2.imshow('h', img_h)
cv2.imshow('v', img_v)
cv2.imwrite(PATH+NAME+'-f_sobel_h.png',img_h)
cv2.imwrite(PATH+NAME+'-f_sobel_v.png',img_v)

a3=filter(img, 'linear', av3)
a5=filter(img, 'linear',av5)
cv2.imshow('a3', a3)
cv2.imshow('a5', a5)
cv2.imwrite(PATH+NAME+'-f_average_3.png',a3)
cv2.imwrite(PATH+NAME+'-f_average_5.png',a5)

img3=filter(img, 'nonlinear', m3)
img5=filter(img,'nonlinear',m5)
cv2.imshow('m3-f', img3)
cv2.imshow('m5f',img5)
cv2.imwrite(PATH+NAME+'-f_median_3.png',img3)
cv2.imwrite(PATH+NAME+'-f_median_5.png',img5)
'''
th=find_th(img)
print(th)
print(img.max())
bi_img=bi_imag(img, th)
cv2.imshow('biimg',bi_img)
print(img)
block_size = 1
binary_adaptive = threshold_local(img, block_size, offset=10)
cv2.imshow('adaptive',binary_adaptive)
print(binary_adaptive)
cv2.waitKey(0)
cv2.destroyAllWindows()

105
192
<ipython-input-5-b6d46e44356b>:20: FutureWarning: The behavior of rgb2gray will change in scikit-image 0.19. Currently, rgb2gray allows 2D grayscale image to be passed as inputs and leaves them unmodified as outputs. Starting from version 0.19, 2D arrays will be treated as 1D images with 3 channels.
  img=rgb2gray(img)
[[0 0 1 ... 1 0 0]
 [0 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 0]
 [0 0 1 ... 1 0 0]]
[[-10. -10.  -9. ...  -9. -10. -10.]
 [-10.  -9.  -9. ...  -9.  -9. -10.]
 [ -9.  -9.  -9. ...  -9.  -9.  -9.]
 ...
 [ -9.  -9.  -9. ...  -9.  -9.  -9.]
 [-10.  -9.  -9. ...  -9.  -9. -10.]
 [-10. -10.  -9. ...  -9. -10. -10.]]
