In [ ]:
import numpy as np
from skimage.filters import median
from spatial_filter import medf
#img=np.random.randint(10,size=(5,5))
img1=np.array([[7, 1, 6, 7,2],
 [9 ,1, 8, 9, 5],
 [4 ,4 ,6 ,3 ,0],
 [8 ,8, 1, 8, 7],
 [0 ,0 ,7, 7 ,5]])
sorted_knl=np.sort(img1, axis=None, kind='quicksort')
print(len(sorted_knl))
print(img1)
img2=medf(3,img1)
print(img2)
img3=median(img1,mode='constant',cval=0.0)
print(img3)

In [ ]:
import numpy as np
def pad_img(img,size):
    m,n=img.shape
    pad_len=int((size-1)/2)#padding length for each edge
    padded_img=np.zeros([m+size-1,n+size-1])
    for i in range(pad_len, pad_len+m):
        for j in range(pad_len, pad_len+n):
            padded_img[i,j]=img[i-pad_len,j-pad_len]
    return padded_img

img1=np.array([[7, 1, 6, 7,2],
 [9 ,1, 8, 9, 5],
 [4 ,4 ,6 ,3 ,0],
 [8 ,8, 1, 8, 7],
 [0 ,0 ,7, 7 ,5]])

img=pad_img(img1,3)
print(img)
print(img.shape)

In [ ]:
import numpy as np
a=np.array([[7, 1, 6, 7,2],
 [9 ,1, 8, 9, 5],
 [4 ,4 ,6 ,3 ,0],
 [8 ,8, 1, 8, 7],
 [0 ,0 ,7, 7 ,5]])
b=np.sort(a,axis=None)
print(a)
print(b)

In [65]:
#import numpy as np
def medft(size,img):
    m,n=img.shape
    kernel=np.zeros([size,size])
    pad_len=int((size-1)/2)
    padded_img=pad_img(img, size)
    new_img=np.zeros([m,n],dtype=np.uint8)
    for i in range(pad_len,pad_len+m):
        for j in range(pad_len,pad_len+n):
            for s in range(0,size):
                for t in range(0,size):
                    p=i-pad_len+s
                    q=j-pad_len+t
                    kernel[s,t]=padded_img[p,q]
                    #print('s',s,'t',t, 'i',p,'j',q)
            sorted_knl=np.sort(kernel, axis=None, kind='quicksort')
            #print(sorted_knl)
            med=sorted_knl[int((size*size-1)/2)]
            new_img[i-pad_len,j-pad_len]=med
    return new_img

a=np.array([[7, 1, 6, 7,2],
            [9 ,1, 8, 9, 5],
            [4 ,4 ,6 ,3 ,0],
            [8 ,8, 1, 8, 7],
            [0 ,0 ,7, 7 ,5]])
print(medft(3,a))

[[0 1 1 5 0]
 [1 6 6 6 2]
 [4 6 6 6 3]
 [0 4 6 6 3]
 [0 0 1 5 0]]


In [63]:

img1=np.array([[7, 1, 6, 7,2],
 [9 ,1, 8, 9, 5],
 [4 ,4 ,6 ,3 ,0],
 [8 ,8, 1, 8, 7],
 [0 ,0 ,7, 7 ,5]])

medf(3,img1)

array([[0, 1, 1, 5, 0],
       [1, 6, 6, 6, 2],
       [4, 6, 6, 6, 3],
       [0, 4, 6, 6, 3],
       [0, 0, 1, 5, 0]], dtype=uint8)